"""UC1 — Predictive Maintenance Operations: analyzes fleet health and generates alerts."""

import pandas as pd
from pathlib import Path
from datetime import timedelta
from typing import Any
from ..config import settings


def _load(filename: str) -> pd.DataFrame:
    return pd.read_csv(Path(settings.DATA_PATH) / filename)


def get_maintenance_risks() -> list[dict[str, Any]]:
    """Score each truck by maintenance risk over the last 90 days."""
    maintenance = _load("maintenance_records.csv")
    utilization = _load("truck_utilization_metrics.csv")
    trucks = _load("trucks.csv")

    maintenance["maintenance_date"] = pd.to_datetime(maintenance["maintenance_date"])
    ref = maintenance["maintenance_date"].max()
    cutoff = ref - timedelta(days=90)
    recent = maintenance[maintenance["maintenance_date"] >= cutoff]

    agg = (
        recent.groupby("truck_id")
        .agg(
            event_count=("maintenance_id", "count"),
            total_cost=("total_cost", "sum"),
            total_downtime=("downtime_hours", "sum"),
        )
        .reset_index()
    )

    latest_util = (
        utilization.sort_values("month", ascending=False)
        .groupby("truck_id")
        .first()
        .reset_index()[["truck_id", "utilization_rate", "average_mpg"]]
    )

    merged = trucks[["truck_id", "unit_number", "make", "model_year", "status"]].merge(
        agg, on="truck_id", how="left"
    ).merge(latest_util, on="truck_id", how="left")

    merged = merged.fillna({"event_count": 0, "total_cost": 0, "total_downtime": 0, "utilization_rate": 0.0, "average_mpg": 0.0})

    def _norm(s: pd.Series) -> pd.Series:
        rng = s.max() - s.min()
        return (s - s.min()) / rng if rng else pd.Series(0.0, index=s.index)

    merged["risk_score"] = (
        _norm(merged["event_count"]) * 0.40
        + _norm(merged["total_cost"]) * 0.35
        + _norm(merged["total_downtime"]) * 0.25
    ).round(3)

    def _level(score: float) -> str:
        if score >= settings.MAINTENANCE_HIGH_RISK_THRESHOLD:
            return "HIGH"
        if score >= 0.35:
            return "MEDIUM"
        return "LOW"

    merged["risk_level"] = merged["risk_score"].apply(_level)
    merged = merged.sort_values("risk_score", ascending=False)

    return merged.to_dict(orient="records")


def get_metrics() -> dict[str, Any]:
    maintenance = _load("maintenance_records.csv")
    maintenance["maintenance_date"] = pd.to_datetime(maintenance["maintenance_date"])
    ref = maintenance["maintenance_date"].max()
    cutoff = ref - timedelta(days=30)
    recent = maintenance[maintenance["maintenance_date"] >= cutoff]

    high_risk = sum(1 for r in get_maintenance_risks() if r["risk_level"] == "HIGH")

    return {
        "total_events_30d": int(len(recent)),
        "total_cost_30d": float(recent["total_cost"].sum()),
        "avg_downtime_hours": float(recent["downtime_hours"].mean()) if len(recent) else 0.0,
        "high_risk_trucks": high_risk,
        "fleet_total": int(_load("trucks.csv").shape[0]),
    }


def build_alert_html(risks: list[dict]) -> str:
    high = [r for r in risks if r["risk_level"] == "HIGH"]
    rows = "".join(
        f"""<tr>
          <td style="padding:8px;border:1px solid #ddd">{r['unit_number']}</td>
          <td style="padding:8px;border:1px solid #ddd">{r['make']} {r['model_year']}</td>
          <td style="padding:8px;border:1px solid #ddd">{int(r.get('event_count',0))}</td>
          <td style="padding:8px;border:1px solid #ddd">${r.get('total_cost',0):,.0f}</td>
          <td style="padding:8px;border:1px solid #ddd">{r.get('total_downtime',0):.1f} hrs</td>
          <td style="padding:8px;border:1px solid #ddd;color:#c0392b;font-weight:bold">{r['risk_score']:.2f}</td>
        </tr>"""
        for r in high
    )
    return f"""
    <html><body style="font-family:Arial,sans-serif">
    <h2 style="color:#c0392b">&#9888; Maintenance Alert — High-Risk Trucks</h2>
    <p>The following trucks require immediate maintenance attention (last 90 days):</p>
    <table style="border-collapse:collapse;width:100%">
      <tr style="background:#f2f2f2">
        <th style="padding:8px;border:1px solid #ddd">Unit</th>
        <th style="padding:8px;border:1px solid #ddd">Vehicle</th>
        <th style="padding:8px;border:1px solid #ddd">Events (90d)</th>
        <th style="padding:8px;border:1px solid #ddd">Cost (90d)</th>
        <th style="padding:8px;border:1px solid #ddd">Downtime</th>
        <th style="padding:8px;border:1px solid #ddd">Risk Score</th>
      </tr>
      {rows}
    </table>
    <p style="color:#666;font-size:12px">Generated by Enterprise RAG — Maintenance Operations Center</p>
    </body></html>
    """
