"""UC2 — Driver Safety & Compliance Command: monitors incidents and flags at-risk drivers."""

import pandas as pd
from pathlib import Path
from datetime import timedelta
from typing import Any
from ..config import settings


def _load(filename: str) -> pd.DataFrame:
    return pd.read_csv(Path(settings.DATA_PATH) / filename)


def get_compliance_status() -> list[dict[str, Any]]:
    """Return compliance flags for every active driver."""
    incidents = _load("safety_incidents.csv")
    drivers = _load("drivers.csv")
    metrics = _load("driver_monthly_metrics.csv")

    incidents["incident_date"] = pd.to_datetime(incidents["incident_date"])
    ref = incidents["incident_date"].max()
    window = ref - timedelta(days=settings.SAFETY_INCIDENT_WINDOW_DAYS)
    recent_inc = incidents[incidents["incident_date"] >= window]

    inc_count = (
        recent_inc.groupby("driver_id")
        .agg(
            recent_incidents=("incident_id", "count"),
            at_fault_count=("at_fault_flag", "sum"),
            preventable_count=("preventable_flag", "sum"),
            total_damage=("vehicle_damage_cost", "sum"),
        )
        .reset_index()
    )

    latest_metrics = (
        metrics.sort_values("month", ascending=False)
        .groupby("driver_id")
        .first()
        .reset_index()[["driver_id", "on_time_delivery_rate", "average_mpg"]]
    )

    active = drivers[drivers["employment_status"] == "Active"].copy()
    merged = active.merge(inc_count, on="driver_id", how="left").merge(
        latest_metrics, on="driver_id", how="left"
    )
    merged = merged.fillna(
        {"recent_incidents": 0, "at_fault_count": 0, "preventable_count": 0, "total_damage": 0}
    )

    merged["flag_incident_spike"] = merged["recent_incidents"] >= 2
    merged["flag_low_ontime"] = merged["on_time_delivery_rate"].fillna(1) < 0.80
    merged["flag_at_fault"] = merged["at_fault_count"] >= 1

    def _status(row) -> str:
        if row["flag_incident_spike"] or row["flag_at_fault"]:
            return "CRITICAL"
        if row["flag_low_ontime"]:
            return "WARNING"
        return "OK"

    merged["compliance_status"] = merged.apply(_status, axis=1)
    merged = merged.sort_values(
        ["compliance_status", "recent_incidents"], ascending=[True, False]
    )

    return merged.to_dict(orient="records")


def get_metrics() -> dict[str, Any]:
    incidents = _load("safety_incidents.csv")
    incidents["incident_date"] = pd.to_datetime(incidents["incident_date"])
    ref = incidents["incident_date"].max()
    cutoff = ref - timedelta(days=30)
    recent = incidents[incidents["incident_date"] >= cutoff]

    status = get_compliance_status()
    critical = sum(1 for d in status if d["compliance_status"] == "CRITICAL")
    warning = sum(1 for d in status if d["compliance_status"] == "WARNING")

    return {
        "incidents_30d": int(len(recent)),
        "at_fault_30d": int(recent["at_fault_flag"].sum()),
        "total_damage_30d": float(recent["vehicle_damage_cost"].sum()),
        "critical_drivers": critical,
        "warning_drivers": warning,
        "active_drivers": int(_load("drivers.csv").query("employment_status == 'Active'").shape[0]),
    }


def build_alert_html(flagged: list[dict]) -> str:
    critical = [d for d in flagged if d["compliance_status"] == "CRITICAL"]
    rows = "".join(
        f"""<tr>
          <td style="padding:8px;border:1px solid #ddd">{d['first_name']} {d['last_name']}</td>
          <td style="padding:8px;border:1px solid #ddd">{d['driver_id']}</td>
          <td style="padding:8px;border:1px solid #ddd">{int(d.get('recent_incidents',0))}</td>
          <td style="padding:8px;border:1px solid #ddd">{int(d.get('at_fault_count',0))}</td>
          <td style="padding:8px;border:1px solid #ddd">${d.get('total_damage',0):,.0f}</td>
          <td style="padding:8px;border:1px solid #ddd;color:#c0392b;font-weight:bold">{d['compliance_status']}</td>
        </tr>"""
        for d in critical
    )
    return f"""
    <html><body style="font-family:Arial,sans-serif">
    <h2 style="color:#e74c3c">&#128272; Safety Compliance Alert</h2>
    <p>Drivers requiring immediate safety review ({settings.SAFETY_INCIDENT_WINDOW_DAYS}-day window):</p>
    <table style="border-collapse:collapse;width:100%">
      <tr style="background:#f2f2f2">
        <th style="padding:8px;border:1px solid #ddd">Driver</th>
        <th style="padding:8px;border:1px solid #ddd">ID</th>
        <th style="padding:8px;border:1px solid #ddd">Incidents</th>
        <th style="padding:8px;border:1px solid #ddd">At-Fault</th>
        <th style="padding:8px;border:1px solid #ddd">Damage</th>
        <th style="padding:8px;border:1px solid #ddd">Status</th>
      </tr>
      {rows}
    </table>
    <p style="color:#666;font-size:12px">Generated by Enterprise RAG — Safety & Compliance Command</p>
    </body></html>
    """
